			<table>
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Apellidos</th>
						<th>Email</th>
						<th>Dirección</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Nombre</td>
						<td>Apellidos</td>
						<td>Email</td>
						<td>Dirección</td>
					</th>
					<tr>
						<td>Nombre</td>
						<td>Apellidos</td>
						<td>Email</td>
						<td>Dirección</td>
					</th>
					<tr>
						<td>Nombre</td>
						<td>Apellidos</td>
						<td>Email</td>
						<td>Dirección</td>
					</th>
					<tr>
						<td>Nombre</td>
						<td>Apellidos</td>
						<td>Email</td>
						<td>Dirección</td>
					</th>
				</tbody>
			</table>
